{% set name = "napari-locpix" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-locpix-{{ version }}.tar.gz
  sha256: 07a81fe97d36b7f633355ffc6e61f8abf5439aad4ff5fcf1d35a191e82aff85a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - napari
    - numpy
    - polars
    - pyarrow
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_locpix
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oubino/napari-locpix
  summary: Load in SMLM data and annotate within napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - oubino
