{% set name = "napari-locpix" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 764ca2f1f80cccbe2344c1f2fea1ab3f2de21b71cc9232a1eeb2c6be56496b16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - napari
    - numpy
    - polars
    - pyarrow
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_locpix
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oubino/napari-locpix
  summary: Load in SMLM data and annotate within napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - oubino
